### ISSUE TITLE
React.js support?

### ISSUE THREAD

**Issue by matheusqro** [glomex/vast-ima-player#13]
The React.js is supported?

**Comment by klipstein** [comment]
Sorry for not seeing your message earlier. This library can also be used in combination with React.js.

I would suggest to layer the DOM as such, without the Video-Tag / Ad-Layer being touched by React:

1. Video-Tag
2. Ad-Layer
3. Your custom controls built with React

You can of course also write a separate React component that renders the above structure and use `componentDidMount` to instantiate the vast-ima-player and `componentWillUnmount` to destroy it.
