### ISSUE TITLE
Check that the Google IMA SDK has been loaded and executed in iframe with Codepen example.

### ISSUE THREAD

**Issue by diablero13** [glomex/vast-ima-player#2]
Add an initial check that the `window.google` object is defined to prevent the example script from crashing without any notifications for user when the loading of Google IMA SDK is blocked by user's ad blockers. 

![foo](https://user-images.githubusercontent.com/468752/83377850-95886580-a3df-11ea-80b2-927e260e13f1.png)

**Example:** https://codepen.io/diablero13/pen/JjGPYYa

**Comment by klipstein** [comment]
Thanks @diablero13. Copied over the JS from your pen to the referenced codepen.
